# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
    ]
